name: Test Master
on:  push

jobs:
  TEST_BACKEND:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 🪜 Setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 🛒 Setup postgres database
        uses: m4nu56/postgresql-action@1.0
        with:
          postgresql version: latest
          postgresql user: postgres
          postgresql password: postgres

      - name: chmod +x ./mvnw
        run:  chmod +x ./mvnw

      - name: 🕋  TEST
        run: ./mvnw test -Dspring.profiles.active=postgres
